---
# LDAP
- name: Configure LDAP auth
  template:
    src: "{{ dovecot_ldap_conf }}.j2"
    dest: "{{ dovecot_dir }}/{{ dovecot_ldap_conf }}"
    mode: 0640
  when: inventory_hostname in groups['imap']
  notify: reload dovecot
  tags: [dovecot_ldap,doveconfig]

- name: Create dovecot-ldap.conf.ext symlink
  file:
    src: "{{ dovecot_dir }}/{{ dovecot_ldap_conf }}"
    dest: "{{ dovecot_dir }}/{{ dovecot_ldap_symlink }}"
    state: link
    owner: "{{ global_owner }}"
    group: "{{ global_group }}"
  when: inventory_hostname in groups['imap']
  tags: [dovecot_ldap,doveconfig]

# Master
- include: master.yml
  when: inventory_hostname in groups['imap']
  tags: [dovecot_ldap,doveconfig,dovemaster]
