---
- name: Install Dovecot MDA and Pigeonhole
  pacman:
    name: dovecot,pigeonhole
    state: present
  when: inventory_hostname in groups['imap']
  tags: [doveconfig]

# Configure Dovecot
- name: Configure dovecot.conf
  copy:
    src: dovecot.conf
    dest: "{{ dovecot_dir }}/dovecot.conf"
    mode: 0644
  when: inventory_hostname in groups['imap']
  notify: reload dovecot
  tags: [doveconfig]

- name: Sync Dovecot config files
  template:
    src: "conf.d/{{ item }}.j2"
    dest: "{{ dovecot_conf_dir }}/{{ item }}"
    backup: no
  when: inventory_hostname in groups['imap']
  notify: reload dovecot
  tags: [doveconfig]
  with_items:
    - "{{ dovecot_conf_files }}"

- name: Create MailCrypt directory
  file:
    path: "{{ dovecot_mcrypt_dir }}"
    state: directory
    owner: "{{ global_owner }}"
    group: "{{ global_group }}"
    mode: 0755
  when: inventory_hostname in groups['imap']
  tags: [dovecrypt]

- name: Create global MailCrypt private key
  shell: "openssl ecparam -name prime256v1 -genkey | openssl pkey -out ecprivkey.pem"
  args:
    chdir: "{{ dovecot_mcrypt_dir }}"
    creates: "ecprivkey.pem"
  notify: reload dovecot
  tags: [dovecrypt]

- name: Create global MailCrypt public key
  shell: "openssl pkey -in ecprivkey.pem -pubout -out ecpubkey.pem"
  args:
    chdir: "{{ dovecot_mcrypt_dir }}"
    creates: "ecpubkey.pem"
  notify: reload dovecot
  tags: [dovecrypt]

- name: Push quota warning script
  copy:
    src: scripts/quota-warning.sh
    dest: /usr/local/bin/quota-warning.sh
    mode: a+x
  when: inventory_hostname in groups['imap']
  tags: [doveconfig]

# Trash
- name: Configure Trash settings
  copy:
    src: "{{ dovecot_trash }}"
    dest: "{{ dovecot_dir }}/{{ dovecot_trash }}"
    mode: 0644
  when: inventory_hostname in groups['imap']
  notify: reload dovecot
  tags: [doveconfig]

# LDAP
- include: ldap.yml
  when: inventory_hostname in groups['imap']
  tags: [dovecot_ldap]

# UFW
- include: ufw.yml
  when: inventory_hostname in groups['imap']
  tags: [ufw]

# Finally ensure Dovecot is running
- name: Enable Dovecot
  systemd:
    name: dovecot
    enabled: yes
    masked: no
    state: started
  when: inventory_hostname in groups['imap']
