---
- name: start pwhois_milter
  systemd:
    name: pwhois_milter
    enabled: yes
    state: started
  become: yes

- name: stop pwhois_milter
  systemd:
    name: pwhois_milter
    enabled: yes
    state: stopped
  become: yes

- name: restart pwhois_milter
  systemd:
    name: pwhois_milter
    enabled: yes
    state: restarted
  become: yes

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
