---
- name: Add virtual mail group
  group:
    name: vmail
    state: present
    gid: 5000
    system: yes

- name: Add virtual mail user
  user:
    name: vmail
    shell: /usr/bin/nologin
    home: /home/vmail
    create_home: True
    uid: 5000
    group: 5000
    system: yes

- name: Ensure mail log directory exists
  file:
    path: "{{ mail_log_dir }}"
    state: directory
    owner: "{{ global_owner }}"
    group: "{{ global_group }}"
    mode: 0755

- name: Sync pacman database
  pacman:
    update_cache: yes

- name: Install dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - icu
