---
- name: Ensure UFW is installed for traffic management
  pacman:
    name: ufw
    state: present
  tags: [ufw]

- name: Ensure UFW is enabled
  systemd:
    name: ufw
    enabled: yes
    masked: no
    state: started

- name: Ensure UFW status is active
  ufw:
    state: enabled
