---
# Make sure UFW is installed for firewall configuration
- name: Ensure UFW is installed for Postfix firewall management
  pacman:
    name: ufw
    state: present
  when: inventory_hostname in groups['smtp']
  tags: [ufw]

# Set firewall rules for Postfix
- name: Set Postfix firewall rules
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - smtp
    - submission
  when: inventory_hostname in groups['smtp']
  tags: [ufw]
