---
- name: start clamd
  systemd:
    name: clamd
    enabled: yes
    state: started
  become: yes

- name: stop clamd
  systemd:
    name: clamd
    enabled: yes
    state: stopped
  become: yes

- name: restart clamd
  systemd:
    name: clamd
    enabled: yes
    state: restarted
  become: yes

- name: freshclam
  systemd:
    name: clamav-freshclam
    enabled: yes
    state: started
  become: yes

- name: stop freshclam
  systemd:
    name: clamav-freshclam
    enabled: yes
    state: stopped
  become: yes

- name: restart freshclam
  systemd:
    name: clamav-freshclam
    enabled: yes
    state: restarted
  become: yes

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
