---
- name: start postgrey
  systemd:
    name: postgrey
    enabled: yes
    state: started
  become: yes

- name: stop postgrey
  systemd:
    name: postgrey
    enabled: yes
    state: stopped
  become: yes

- name: restart postgrey
  systemd:
    name: postgrey
    enabled: yes
    state: restarted
  become: yes

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
