---
sasl_ldap_hosts: "ldap://ldap1.domain.tld ldap://ldap2.domain.tld ldap://ldap3.domain.tld"
sasldest: "/etc/saslauthd.conf"
sasldest2: "/etc/conf.d/saslauthd"
sasldest3: "/usr/lib/sasl2/smtpd.conf"
