---
- name: start solr
  systemd:
    name: solr
    enabled: yes
    state: started
  become: yes

- name: stop solr
  systemd:
    name: solr
    enabled: yes
    state: stopped
  become: yes

- name: restart solr
  systemd:
    name: solr
    enabled: yes
    state: restarted
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
