---
- name: start opendmarc
  systemd:
    name: opendmarc
    enabled: yes
    state: started
  become: yes

- name: stop opendmarc
  systemd:
    name: opendmarc
    enabled: yes
    state: stopped
  become: yes

- name: restart opendmarc
  systemd:
    name: opendmarc
    enabled: yes
    state: restarted
  become: yes

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
