---
- name: Install OpenDMARC and dependencies to generate DMARC reports
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - opendmarc
    - perl-switch
    - perl-libwww

- name: Copy custom systemd opendmarc.service file to /etc/systemd/system/
  copy: >
    src=opendmarc.service
    dest=/etc/systemd/system/opendmarc.service
    mode=644
  notify: reload systemd daemon

- name: Automatically create socket directory
  copy: >
    src=tmpfiles.d/opendmarc.conf
    dest=/etc/tmpfiles.d/opendmarc.conf
  notify: restart opendmarc

- name: Sync OpenDMARC configuration
  template:
    src: opendmarc.conf.j2
    dest: "{{ opendmarc_dir }}/opendmarc.conf"
    owner: opendmarc
    group: mail
    mode: 0640
  notify: restart opendmarc
  tags: [opendmarc]

- name: Ensure OpenDMARC is enabled
  systemd:
    name: opendmarc
    enabled: yes
    masked: no
    state: started
