---
- name: Install milter dependency
  pacman:
    name: libmilter
    state: present

- name: Ensure Prefix WhoIs Milter is installed
  aur:
    name: pwhois_milter
    user: "{{ ansible_user_id }}"
  notify: restart pwhois_milter

- name: Create PWhois directory
  file:
    path: /run/pwhois_milter
    state: directory
    owner: postfix
    group: postfix
    mode: 0755

# Finally ensure PWhois is running
- name: Enable PWhois_Milter
  systemd:
    name: pwhois_milter
    enabled: yes
    masked: no
    state: started
