---
# Ensure Pyzor is installed
- name: Ensure Pyzor is installed
  aur:
    name: pyzor
    user: "{{ ansible_user_id }}"
  when: inventory_hostname in groups['smtp']

# Set firewall rule to open UDP for Pyzor
- name: Port forward Pyzor UDP port 24441
  ufw: rule=allow port=24441 proto=udp
  when: inventory_hostname in groups['smtp']
  tags: [ufw]
  ignore_errors: yes

