---
postfix_conf_dir: "/etc/postfix"
postfix_ssl_dir: "/etc/postfix/ssl"
postfix_ssl_cert: "{{ tls_cert }}"
postfix_ssl_key: "{{ tls_key_cert }}"
postfix_ssl_chain: "{{ tls_chain_cert }}"
postfix_config_file: "{{ postfix_conf_dir }}/main.cf"
postfix_master_file: "{{ postfix_conf_dir }}/master.cf"
header_checks_config: "{{ postfix_conf_dir }}/header_checks"
sender_access_config: "{{ postfix_conf_dir }}/sender_access"
smtp_header_checks_config: "{{ postfix_conf_dir }}/smtp_header_checks"
postscreen_access_list: "{{ postfix_conf_dir }}/postscreen_access.cidr"
postscreen_dnsbl_list:
  - zen.spamhaus.org*2
  - xbl.spamhaus.org*2
  - sbl.spamhaus.org*2
  - pbl.spamhaus.org*2
  - ix.dnsbl.manitu.net*1
  - bl.spamcop.net*1
  - b.barracudacentral.org*1
postfix_inet_interfaces: "all"
postfix_message_size_limit: "20480000"
postfix_virtual_mailbox_base: "/home/vmail/"
postfix_reject_rbl_client:
  - b.barracudacentral.org
  - bl.spamcop.net
  - ix.dnsbl.manitu.net
  - pbl.spamhaus.org
  - sbl.spamhaus.org
  - xbl.spamhaus.org
  - zen.spamhaus.org

# LDAP
postfix_ldap_dir: "{{ postfix_conf_dir }}/ldap"
ldap_vmailbox: "ldap-vmailbox.cf"
ldap_aliases: "ldap-aliases.cf"
ldap_domains: "ldap-virtual-domains.cf"
ldap_forward: "ldap-forward.cf"
ldap_groups: "ldap-groups.cf"
ldap_servers:
  - ldapserver1
  - ldapserver2
  - ldapserver3
ldap_mail_search_base: "ou=Mail,dc=domain,dc=tld"
ldap_mail_groups_search_base: "ou=Groups,ou=Mail,dc=domain,dc=tld"
ldap_mail_domains_search_base: "ou=Domains,dc=domain,dc=tld"
ldap_bind: "no"
starttls: "yes"
requiretls: "yes"
