---
dovecot_dir: "/etc/dovecot"
dovecot_default_fields_home: "/home/vmail"
dovecot_mcrypt_dir: "{{ dovecot_dir }}/mcrypt"
dovecot_ssl_dir: "{{ dovecot_dir }}/ssl"
dovecot_conf_dir: "{{ dovecot_dir }}/conf.d"
dovecot_conf_files:
  - 10-auth.conf
  - 10-director.conf
  - 10-logging.conf
  - 10-mail.conf
  - 10-master.conf
  - 10-ssl.conf
  - 15-lda.conf
  - 15-mailboxes.conf
  - 20-imap.conf
  - 20-lmtp.conf
  - 20-managesieve.conf
  - 20-pop3.conf
  - 20-submission.conf
  - 90-acl.conf
  - 90-plugin.conf
  - 90-quota.conf
  - 90-sieve-extprograms.conf
  - 90-sieve.conf
  - 99-replicator.conf
  - auth-checkpassword.conf.ext
  - auth-deny.conf.ext
  - auth-dict.conf.ext
  - auth-ldap.conf.ext
  - auth-master.conf.ext
  - auth-passwdfile.conf.ext
  - auth-static.conf.ext
  - auth-system.conf.ext
dovecot_trash: "dovecot-trash.conf.ext"
dovecot_ldap_hosts: "ldap1.domain.tld ldap2.domain.tld ldap3.domain.tld"
dovecot_ldap_conf: "dovecot-ldap.conf.ext"
dovecot_ldap_master: "dovecot-ldap-masteruser.conf.ext"
dovecot_ldap_symlink: "dovecot-ldap-userdb.conf.ext"
dovecot_ldap_tls: "yes"
dovecot_ldap_auth_bind: "no"
dovecot_ldap_password_lookup_dn: "uid=dovecot,ou=something,dc=domain,dc=tld"
dovecot_ldap_password_lookup_dnpass:

  create with ->  ansible-vault encrypt_string 'secretpw' --name 'dovecot_ldap_password_lookup_dnpass'

dovecot_submission_host: "mail.{{ domain }}"
dovecot_error_log: "{{ mail_log_dir }}/mail.err"
dovecot_mail_log: "{{ mail_log_dir }}/mail.log"
dovecot_auth_verbose: "yes"
dovecot_auth_debug: "no"
dovecot_mail_debug: "no"
dovecot_verbose_ssl: "no"
doveadm_password:
 
  create with ->  ansible-vault encrypt_string 'secretpw' --name 'doveadm_password'

replication_full_sync_interval: 1
replication_max_conns: 100
replication_dsync_parameters: "-d -N -l 30 -U"
